name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  files-changed:
    uses: ./.github/workflows/files-changed.yml

  lint:
    if: needs.files-changed.outputs.lint == 'true' || needs.files-changed.outputs.actions == 'true'
    needs: files-changed
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true
    - name: Setup golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        skip-cache: true
        args: --timeout=10m --verbose
  test:
    if: needs.files-changed.outputs.app == 'true' || needs.files-changed.outputs.actions == 'true'
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true
    - name: Install tools
      run: make tools
    - name: Run generate templ files
      run: make generate
    - name: Run tests
      run: make test
  build:
    if: needs.files-changed.outputs.app == 'true' || needs.files-changed.outputs.actions == 'true'
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true
    - name: Install tools
      run: make tools
    - name: Build
      run: make build
